/**
 * Ratnawala — MongoDB Seed Script
 * Seeds all 36 gemstones + creates a default admin account.
 *
 * Usage:
 *   node scripts/seedGems.js            # seed gems (skips existing)
 *   node scripts/seedGems.js --admin    # also creates/updates admin user
 *   node scripts/seedGems.js --wipe     # wipe gems collection first
 */

require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const mongoose = require('mongoose');
const bcrypt   = require('bcryptjs');

// ── Inline gem data (CommonJS-compatible extract from client/src/data/gemstones.js) ──
const GEMS = [
  { slug:'yellow-sapphire', name:'Yellow Sapphire',   nameHindi:'पुखराज',   planet:'Jupiter', planetSymbol:'♃', zodiac:['Sagittarius','Pisces'],   accentColor:'#F4C842', accentColorLight:'#FDF3C0', color:['Yellow','Golden','Pale Yellow'],  transparency:'transparent', mines:['Ceylon (Sri Lanka)','Bangkok (Thailand)','Australia','Madagascar'], qualities:['A','AA','AAA','Natural Unheated'], weightRange:{min:2,max:15},  hardness:9,  family:'Corundum',    description:'Yellow Sapphire, known as Pukhraj, is the gemstone of Jupiter — the planet of wisdom, wealth, and fortune.', astrologicalBenefits:['Wealth & prosperity','Higher education & wisdom','Marital harmony','Good health','Spiritual growth'], whoShouldWear:'Recommended for Sagittarius and Pisces ascendants.', bestMetal:'Gold',    wearingFinger:'Index finger',  featured:true,  isNavRatan:true },
  { slug:'blue-sapphire',   name:'Blue Sapphire',     nameHindi:'नीलम',     planet:'Saturn',  planetSymbol:'♄', zodiac:['Capricorn','Aquarius'],    accentColor:'#4A90D9', accentColorLight:'#DBEAFE', color:['Blue','Royal Blue','Cornflower'], transparency:'transparent', mines:['Ceylon (Sri Lanka)','Kashmir (India)','Burma (Myanmar)'],       qualities:['A','AA','AAA','Natural Unheated'], weightRange:{min:2,max:12},  hardness:9,  family:'Corundum',    description:'Blue Sapphire, known as Neelam, is the gemstone of Saturn — one of the fastest-acting stones in Vedic astrology.', astrologicalBenefits:['Career success','Wealth accumulation','Mental clarity','Protection from evil eye','Discipline'], whoShouldWear:'Best for Capricorn and Aquarius ascendants.', bestMetal:'Silver or Panchdhatu', wearingFinger:'Middle finger', featured:true,  isNavRatan:true },
  { slug:'ruby',            name:'Ruby',               nameHindi:'मानिक',    planet:'Sun',     planetSymbol:'☀', zodiac:['Leo'],                     accentColor:'#E02020', accentColorLight:'#FEE2E2', color:['Red','Pigeon Blood','Pink-Red'],  transparency:'transparent', mines:['Burma (Myanmar)','Mozambique','Thailand','Afghanistan'],        qualities:['A','AA','AAA','Pigeon Blood'],      weightRange:{min:1,max:10},  hardness:9,  family:'Corundum',    description:'Ruby, known as Manik, is the gemstone of the Sun — representing vitality, leadership, and royal power.', astrologicalBenefits:['Leadership & confidence','Government favour','Good health & vitality','Father\'s blessings','Fame'], whoShouldWear:'Best for Leo ascendants and those in government or politics.', bestMetal:'Gold', wearingFinger:'Ring finger', featured:true,  isNavRatan:true },
  { slug:'emerald',         name:'Emerald',            nameHindi:'पन्ना',    planet:'Mercury', planetSymbol:'☿', zodiac:['Gemini','Virgo'],           accentColor:'#10B981', accentColorLight:'#D1FAE5', color:['Green','Deep Green','Bluish Green'], transparency:'transparent', mines:['Colombia','Zambia','Brazil','Zimbabwe'],                       qualities:['F1','F2','F3','Commercial'],        weightRange:{min:2,max:12},  hardness:7.5,family:'Beryl',       description:'Emerald, known as Panna, is the gemstone of Mercury — governing communication, intelligence, and commerce.', astrologicalBenefits:['Intelligence & memory','Business success','Communication skills','Creative expression','Health'], whoShouldWear:'Best for Gemini and Virgo ascendants.', bestMetal:'Gold or Silver', wearingFinger:'Little finger', featured:true,  isNavRatan:true },
  { slug:'diamond',         name:'Diamond',            nameHindi:'हीरा',     planet:'Venus',   planetSymbol:'♀', zodiac:['Taurus','Libra'],          accentColor:'#94A3B8', accentColorLight:'#F1F5F9', color:['White','Yellow','Pink','Blue'],   transparency:'transparent', mines:['India','South Africa','Russia','Botswana'],                    qualities:['D-F','G-J','K-M','Commercial'],     weightRange:{min:0.25,max:5}, hardness:10, family:'Diamond',     description:'Diamond, known as Heera, is the gemstone of Venus — representing luxury, beauty, and artistic brilliance.', astrologicalBenefits:['Luxury & comfort','Creative talent','Romantic relationships','Financial prosperity','Artistic success'], whoShouldWear:'Best for Taurus and Libra ascendants.', bestMetal:'Gold or Platinum', wearingFinger:'Ring finger', featured:true,  isNavRatan:true },
  { slug:'coral',           name:'Red Coral',          nameHindi:'मूंगा',    planet:'Mars',    planetSymbol:'♂', zodiac:['Aries','Scorpio'],         accentColor:'#F97316', accentColorLight:'#FEF3C7', color:['Red','Ox Blood','Pink'],         transparency:'opaque',      mines:['Mediterranean Sea','Japan','Australia'],                       qualities:['A','AA','AAA'],                    weightRange:{min:3,max:15},  hardness:3.5,family:'Organic',     description:'Red Coral, known as Moonga, is the gemstone of Mars — providing courage, energy, and protection.', astrologicalBenefits:['Courage & confidence','Health & vitality','Protection from enemies','Mangal dosh remedy','Athletic performance'], whoShouldWear:'Best for Aries and Scorpio ascendants.', bestMetal:'Gold or Silver', wearingFinger:'Ring finger', featured:false, isNavRatan:true },
  { slug:'pearl',           name:'Pearl',              nameHindi:'मोती',     planet:'Moon',    planetSymbol:'☽', zodiac:['Cancer'],                  accentColor:'#E2E8F0', accentColorLight:'#F8FAFC', color:['White','Cream','Pink'],          transparency:'opaque',      mines:['Persian Gulf','Ceylon','Basra','South Sea'],                   qualities:['A','AA','AAA','Natural'],           weightRange:{min:3,max:12},  hardness:2.5,family:'Organic',     description:'Pearl, known as Moti, is the gemstone of the Moon — bringing calm, emotional balance, and maternal blessings.', astrologicalBenefits:['Emotional stability','Mental peace','Good memory','Mother\'s blessings','Prosperity'], whoShouldWear:'Best for Cancer ascendants.', bestMetal:'Silver', wearingFinger:'Little finger', featured:false, isNavRatan:true },
  { slug:'hessonite',       name:'Hessonite Garnet',   nameHindi:'गोमेद',    planet:'Rahu',    planetSymbol:'☊', zodiac:['Aquarius','Gemini'],        accentColor:'#D97706', accentColorLight:'#FEF3C7', color:['Honey','Brown-Orange','Golden'], transparency:'transparent', mines:['Ceylon (Sri Lanka)','India','Brazil'],                          qualities:['A','AA','AAA','Natural'],           weightRange:{min:3,max:15},  hardness:7,  family:'Garnet',      description:'Hessonite, known as Gomed, is the gemstone of Rahu — one of the shadow planets in Vedic astrology.', astrologicalBenefits:['Rahu dasha relief','Career clarity','Freedom from confusion','Mental strength','Success in unconventional fields'], whoShouldWear:'Recommended during Rahu mahadasha.', bestMetal:'Panchdhatu', wearingFinger:'Middle finger', featured:false, isNavRatan:true },
  { slug:'cats-eye',        name:"Cat's Eye",          nameHindi:'लहसुनिया',  planet:'Ketu',    planetSymbol:'☋', zodiac:['Pisces','Sagittarius'],     accentColor:'#92400E', accentColorLight:'#FEF3C7', color:['Grey-Green','Brown','Honey'],    transparency:'translucent', mines:['Ceylon (Sri Lanka)','South India','Brazil'],                   qualities:['A','AA','AAA'],                    weightRange:{min:3,max:12},  hardness:8.5,family:'Chrysoberyl',description:"Cat's Eye Chrysoberyl, known as Lahasuniya, is the gemstone of Ketu — the south node of the moon.", astrologicalBenefits:['Ketu dasha relief','Spiritual growth','Protection from accidents','Release from past karma','Intuition'], whoShouldWear:'Recommended during Ketu mahadasha.', bestMetal:'Silver', wearingFinger:'Middle or Index finger', featured:false, isNavRatan:true },
  { slug:'amethyst',        name:'Amethyst',           nameHindi:'जमुनिया',  planet:'Saturn',  planetSymbol:'♄', zodiac:['Aquarius','Capricorn'],     accentColor:'#7C3AED', accentColorLight:'#EDE9FE', color:['Purple','Violet','Light Purple'], transparency:'transparent', mines:['Brazil','Uruguay','Zambia'],                                   qualities:['A','AA','AAA'],                    weightRange:{min:5,max:30},  hardness:7,  family:'Quartz',      description:'Amethyst known as Jamunia is a purple variety of quartz associated with Saturn and Rahu.', astrologicalBenefits:['Mental peace','Protection from negative energy','Spiritual development','Stress relief','Clarity of mind'], whoShouldWear:'Best as a sub-stone for Saturn or Rahu.', bestMetal:'Silver', wearingFinger:'Middle finger', featured:false, isNavRatan:false },
  { slug:'moon-stone',      name:'Moon Stone',         nameHindi:'चन्द्रकांत', planet:'Moon',  planetSymbol:'☽', zodiac:['Cancer','Libra','Scorpio'], accentColor:'#E2E8F0', accentColorLight:'#F8FAFC', color:['Peach','White','Rainbow'],      transparency:'translucent', mines:['Sri Lanka','India','Australia'],                                qualities:['A','AA','AAA'],                    weightRange:{min:3,max:20},  hardness:6,  family:'Feldspar',    description:'Moonstone, known as Chandrakant, exhibits a beautiful adularescence effect reminiscent of moonlight.', astrologicalBenefits:['Emotional balance','Intuition','Travel protection','Feminine energy','Romance'], whoShouldWear:'Best for Cancer ascendants.', bestMetal:'Silver', wearingFinger:'Little finger', featured:false, isNavRatan:false },
  { slug:'opal',            name:'Opal',               nameHindi:'दूधिया पत्थर', planet:'Venus', planetSymbol:'♀', zodiac:['Libra','Taurus'],       accentColor:'#06B6D4', accentColorLight:'#CFFAFE', color:['Play-of-color','White','Fire'],  transparency:'translucent', mines:['Australia','Ethiopia','Mexico'],                                qualities:['A','AA','AAA'],                    weightRange:{min:3,max:15},  hardness:6,  family:'Mineraloid',  description:'Opal with its unique play-of-color is a sub-stone for Venus, enhancing creativity and artistic talent.', astrologicalBenefits:['Creativity','Emotional expression','Romantic love','Artistic talent','Financial prosperity'], whoShouldWear:'Sub-stone for Venus, for Taurus and Libra.', bestMetal:'Silver', wearingFinger:'Ring finger', featured:false, isNavRatan:false },
  { slug:'turquoise',       name:'Turquoise',          nameHindi:'फिरोजा',   planet:'Jupiter', planetSymbol:'♃', zodiac:['Sagittarius','Pisces'],     accentColor:'#0D9488', accentColorLight:'#CCFBF1', color:['Blue-Green','Sky Blue','Green'], transparency:'opaque',      mines:['Iran (Persian)','USA(Arizona)','Tibet'],                        qualities:['A','AA','Natural'],                weightRange:{min:5,max:25},  hardness:5.5,family:'Triclinic',   description:'Turquoise, known as Firoza, is a sub-stone for Jupiter used for protection and good fortune.', astrologicalBenefits:['Protection during travel','Good fortune','Leadership','Communication','Healing'], whoShouldWear:'Sub-stone for Jupiter, worn by Sagittarius.', bestMetal:'Silver', wearingFinger:'Index finger', featured:false, isNavRatan:false },
  { slug:'citrine',         name:'Citrine',            nameHindi:'सुनहला',   planet:'Jupiter', planetSymbol:'♃', zodiac:['Sagittarius','Aries','Leo'], accentColor:'#F59E0B', accentColorLight:'#FEF3C7', color:['Yellow','Golden','Pale Yellow'], transparency:'transparent', mines:['Brazil','Bolivia','Spain'],                                    qualities:['A','AA','AAA'],                    weightRange:{min:5,max:30},  hardness:7,  family:'Quartz',      description:'Citrine, known as Sunehla, is a yellow variety of quartz used as an affordable sub-stone for Jupiter.', astrologicalBenefits:['Wealth attraction','Mental clarity','Positivity','Business success','Confidence'], whoShouldWear:'Sub-stone for Yellow Sapphire.', bestMetal:'Gold', wearingFinger:'Index finger', featured:false, isNavRatan:false },
  { slug:'tourmaline',      name:'Tourmaline',         nameHindi:'टूरमलीन',  planet:'Venus',   planetSymbol:'♀', zodiac:['Libra','Virgo'],           accentColor:'#EC4899', accentColorLight:'#FCE7F3', color:['Pink','Green','Blue','Watermelon'], transparency:'transparent', mines:['Brazil','Afghanistan','Nigeria','USA'],                        qualities:['A','AA','AAA','Paraiba'],           weightRange:{min:2,max:15},  hardness:7.5,family:'Cyclosilicate', description:'Tourmaline comes in a stunning array of colors and is used as a sub-stone for Venus.', astrologicalBenefits:['Creativity','Emotional healing','Positive energy','Protection','Love'], whoShouldWear:'Sub-stone for Venus.', bestMetal:'Silver', wearingFinger:'Ring finger', featured:false, isNavRatan:false },
  { slug:'spinel',          name:'Spinel',             nameHindi:'स्पिनल',   planet:'Mars',    planetSymbol:'♂', zodiac:['Aries','Scorpio'],         accentColor:'#BE123C', accentColorLight:'#FFE4E6', color:['Red','Pink','Blue','Black'],     transparency:'transparent', mines:['Burma','Sri Lanka','Afghanistan'],                              qualities:['A','AA','AAA'],                    weightRange:{min:2,max:10},  hardness:8,  family:'Cubic',       description:'Spinel is a rare gemstone often confused with ruby, used as a sub-stone for Mars.', astrologicalBenefits:['Energy','Courage','Motivation','Passion','Metabolism boost'], whoShouldWear:'Sub-stone for Red Coral.', bestMetal:'Gold', wearingFinger:'Ring finger', featured:false, isNavRatan:false },
  { slug:'lapis-lazuli',    name:'Lapis Lazuli',       nameHindi:'लाजवर्त',  planet:'Saturn',  planetSymbol:'♄', zodiac:['Capricorn','Aquarius'],     accentColor:'#1E3A8A', accentColorLight:'#DBEAFE', color:['Deep Blue','Royal Blue with Gold'], transparency:'opaque',   mines:['Afghanistan','Chile','Russia'],                                 qualities:['A','AA'],                          weightRange:{min:5,max:30},  hardness:5,  family:'Metamorphic', description:'Lapis Lazuli, known as Lajvart, has been prized since antiquity for its intense blue color and golden flecks.', astrologicalBenefits:['Wisdom','Truth','Spiritual clarity','Communication','Inner power'], whoShouldWear:'Sub-stone for Saturn, used for Capricorn.', bestMetal:'Silver', wearingFinger:'Middle finger', featured:false, isNavRatan:false },
  { slug:'peridot',         name:'Peridot',            nameHindi:'पेरिडॉट',  planet:'Mercury', planetSymbol:'☿', zodiac:['Virgo','Gemini'],           accentColor:'#65A30D', accentColorLight:'#ECFCCB', color:['Olive Green','Yellow-Green'],    transparency:'transparent', mines:['Egypt','Pakistan','Myanmar','USA'],                            qualities:['A','AA'],                          weightRange:{min:2,max:15},  hardness:6.5,family:'Orthosil.',   description:'Peridot is a sub-stone for Mercury, offering the benefits of Emerald at a more accessible price.', astrologicalBenefits:['Intelligence','Quick thinking','Business acumen','Communication','Digestion health'], whoShouldWear:'Sub-stone for Emerald.', bestMetal:'Gold or Silver', wearingFinger:'Little finger', featured:false, isNavRatan:false },
  { slug:'iolite',          name:'Iolite',             nameHindi:'आयोलाइट',  planet:'Saturn',  planetSymbol:'♄', zodiac:['Aquarius','Libra'],         accentColor:'#4338CA', accentColorLight:'#EEF2FF', color:['Violet-Blue','Blue','Indigo'],   transparency:'transparent', mines:['India','Sri Lanka','Brazil'],                                  qualities:['A','AA'],                          weightRange:{min:2,max:12},  hardness:7,  family:'Inosilicate', description:'Iolite, the "water sapphire", is a sub-stone for Blue Sapphire, resonating with Saturn\'s energies.', astrologicalBenefits:['Clarity of thought','Intuition','Leadership','Financial stability','Career growth'], whoShouldWear:'Sub-stone for Blue Sapphire.', bestMetal:'Silver', wearingFinger:'Middle finger', featured:false, isNavRatan:false },
  { slug:'zircon',          name:'Zircon',             nameHindi:'जर्कन',    planet:'Venus',   planetSymbol:'♀', zodiac:['Virgo','Libra'],            accentColor:'#14B8A6', accentColorLight:'#CCFBF1', color:['Colorless','Blue','Golden'],     transparency:'transparent', mines:['Cambodia','Sri Lanka','Myanmar'],                              qualities:['A','AA','AAA'],                    weightRange:{min:2,max:12},  hardness:7.5,family:'Nesosil.',   description:'Zircon, known as Jarkan, is a natural sub-stone for Diamond, resonating with Venus.', astrologicalBenefits:['Beauty & charm','Luxury','Romantic success','Artistic talent','Prosperity'], whoShouldWear:'Sub-stone for Diamond.', bestMetal:'Silver', wearingFinger:'Ring finger', featured:false, isNavRatan:false },
  { slug:'aquamarine',      name:'Aquamarine',         nameHindi:'एक्वामरीन', planet:'Saturn', planetSymbol:'♄', zodiac:['Pisces','Gemini'],           accentColor:'#7DD3FC', accentColorLight:'#E0F2FE', color:['Light Blue','Sea Blue','Green-Blue'], transparency:'transparent', mines:['Brazil','Pakistan','Mozambique'],                             qualities:['A','AA'],                          weightRange:{min:2,max:15},  hardness:7.5,family:'Beryl',       description:'Aquamarine, with its sea-blue color, is associated with clarity, calm, and Saturn\'s disciplined energy.', astrologicalBenefits:['Clarity of communication','Calm & peace','Travel safety','Courage','Emotional healing'], whoShouldWear:'For Pisces and Gemini ascendants.', bestMetal:'Silver', wearingFinger:'Middle finger', featured:false, isNavRatan:false },
  { slug:'alexandrite',     name:'Alexandrite',        nameHindi:'अलेक्जेंड्राइट', planet:'Mercury', planetSymbol:'☿', zodiac:['Gemini'],          accentColor:'#059669', accentColorLight:'#D1FAE5', color:['Green (daylight)','Red (incandescent)'], transparency:'transparent', mines:['Russia','Brazil','Sri Lanka'],                               qualities:['A','AA','Natural'],                weightRange:{min:0.5,max:5},  hardness:8.5,family:'Chrysoberyl',description:'Alexandrite is a rare colour-changing gemstone, shifting from green in daylight to red under incandescent light.', astrologicalBenefits:['Adaptability','Intelligence','Success in arts & sciences','Prosperity','Good luck'], whoShouldWear:'For Gemini ascendants.', bestMetal:'Gold', wearingFinger:'Little finger', featured:false, isNavRatan:false },
  { slug:'garnet',          name:'Garnet',             nameHindi:'गार्नेट',  planet:'Mars',    planetSymbol:'♂', zodiac:['Capricorn','Aries'],        accentColor:'#9F1239', accentColorLight:'#FFE4E6', color:['Dark Red','Orange','Green'],     transparency:'transparent', mines:['India','Brazil','USA','Africa'],                               qualities:['A','AA','AAA'],                    weightRange:{min:3,max:20},  hardness:7,  family:'Garnet',      description:'Garnet, known as Tamra Mani, is a powerful stone for Mars energy, vitality, and passion.', astrologicalBenefits:['Passion & drive','Physical health','Courage','Grounding','Root chakra activation'], whoShouldWear:'Sub-stone for Red Coral.', bestMetal:'Gold or Copper', wearingFinger:'Ring finger', featured:false, isNavRatan:false },
  { slug:'tanzanite',       name:'Tanzanite',          nameHindi:'तंजानाइट', planet:'Saturn',  planetSymbol:'♄', zodiac:['Sagittarius','Pisces'],     accentColor:'#4F46E5', accentColorLight:'#EEF2FF', color:['Blue-Violet','Purple-Blue'],     transparency:'transparent', mines:['Tanzania (Merelani Hills)'],                                   qualities:['A','AA','AAA'],                    weightRange:{min:1,max:8},   hardness:6.5,family:'Sorosilicate', description:'Tanzanite, found only near Mount Kilimanjaro, is a rare and valuable gemstone with Saturn resonance.', astrologicalBenefits:['Spiritual elevation','Consciousness expansion','Insight','Saturn pacification','Meditation'], whoShouldWear:'For Saturn-influenced ascendants.', bestMetal:'Silver', wearingFinger:'Middle finger', featured:false, isNavRatan:false },
  { slug:'kunzite',         name:'Kunzite',            nameHindi:'कुंजाइट',  planet:'Venus',   planetSymbol:'♀', zodiac:['Taurus','Cancer'],          accentColor:'#E879F9', accentColorLight:'#FDF4FF', color:['Pink','Lilac','Violet'],         transparency:'transparent', mines:['Afghanistan','Brazil','USA'],                                  qualities:['A','AA'],                          weightRange:{min:3,max:20},  hardness:6.5,family:'Pyroxene',    description:'Kunzite is a pastel pink gemstone known for its healing energy and connection to Venus and the heart.', astrologicalBenefits:['Emotional healing','Self-love','Compassion','Peace','Relationship harmony'], whoShouldWear:'For Taurus ascendants as Venus sub-stone.', bestMetal:'Silver', wearingFinger:'Ring finger', featured:false, isNavRatan:false },
  { slug:'morganite',       name:'Morganite',          nameHindi:'मोर्गेनाइट', planet:'Venus',  planetSymbol:'♀', zodiac:['Libra','Taurus'],           accentColor:'#FBCFE8', accentColorLight:'#FDF2F8', color:['Peach','Pink','Salmon'],         transparency:'transparent', mines:['Brazil','Madagascar','Afghanistan'],                           qualities:['A','AA'],                          weightRange:{min:2,max:15},  hardness:7.5,family:'Beryl',       description:'Morganite, the pink beryl, radiates gentle Venus energy with its warm peach-pink color.', astrologicalBenefits:['Divine love','Compassion','Emotional balance','Attraction','Financial abundance'], whoShouldWear:'Sub-stone for Venus, best for Libra.', bestMetal:'Gold', wearingFinger:'Ring finger', featured:false, isNavRatan:false },
  { slug:'prehnite',        name:'Prehnite',           nameHindi:'प्रेहनाइट', planet:'Mercury', planetSymbol:'☿', zodiac:['Virgo','Libra'],            accentColor:'#A3E635', accentColorLight:'#F7FEE7', color:['Pale Green','Yellow-Green'],     transparency:'translucent', mines:['Australia','China','Mali'],                                    qualities:['A','AA'],                          weightRange:{min:5,max:25},  hardness:6,  family:'Phyllosil.',  description:'Prehnite is a calming stone of Mercury resonance, often called the "stone of unconditional love".', astrologicalBenefits:['Prophetic ability','Inner knowing','Peace','Decluttering the mind','Healing'], whoShouldWear:'For Virgo and Libra.', bestMetal:'Silver', wearingFinger:'Little finger', featured:false, isNavRatan:false },
  { slug:'labradorite',     name:'Labradorite',        nameHindi:'लेब्राडोराइट', planet:'Moon', planetSymbol:'☽', zodiac:['Leo','Scorpio','Sagittarius'], accentColor:'#60A5FA', accentColorLight:'#EFF6FF', color:['Grey with Blue/Gold flash'], transparency:'opaque',      mines:['Canada','Madagascar','Finland'],                               qualities:['A','AA'],                          weightRange:{min:5,max:30},  hardness:6,  family:'Feldspar',    description:'Labradorite is famous for its stunning iridescent "labradorescence" and is connected to the Moon and Rahu.', astrologicalBenefits:['Transformation','Magic & synchronicity','Psychic abilities','Protection during change','Intuition'], whoShouldWear:'For Moon and Rahu-influenced ascendants.', bestMetal:'Silver', wearingFinger:'Ring finger', featured:false, isNavRatan:false },
  { slug:'rhodonite',       name:'Rhodonite',          nameHindi:'रोडोनाइट',  planet:'Mars',   planetSymbol:'♂', zodiac:['Taurus','Aries'],           accentColor:'#F43F5E', accentColorLight:'#FFE4E6', color:['Pink','Red with Black'],        transparency:'opaque',      mines:['Russia','Australia','India'],                                  qualities:['A','AA'],                          weightRange:{min:5,max:25},  hardness:6,  family:'Inosilicate', description:'Rhodonite, with its deep pink-red color and black veining, is associated with compassion and Mars energy.', astrologicalBenefits:['Emotional healing after trauma','Forgiveness','Confidence','Romantic love','Courage'], whoShouldWear:'For Aries and Mars-influenced ascendants.', bestMetal:'Copper', wearingFinger:'Ring finger', featured:false, isNavRatan:false },
  { slug:'rhodochrosite',   name:'Rhodochrosite',      nameHindi:'रोडोक्रोसाइट', planet:'Mars', planetSymbol:'♂', zodiac:['Leo','Scorpio'],         accentColor:'#FB7185', accentColorLight:'#FFF1F2', color:['Pink','Light Red','Banded'],    transparency:'translucent', mines:['Argentina','Peru','South Africa'],                             qualities:['A','AA'],                          weightRange:{min:3,max:20},  hardness:4,  family:'Carbonate',   description:'Rhodochrosite, called the "Inca Rose", is a stone of compassionate love and inner child healing.', astrologicalBenefits:['Self-love','Childhood trauma healing','Creativity','Positive outlook','Joy'], whoShouldWear:'For Leo and emotional healing purposes.', bestMetal:'Silver', wearingFinger:'Ring finger', featured:false, isNavRatan:false },
  { slug:'carnelian',       name:'Carnelian',          nameHindi:'कर्नेलियन', planet:'Mars',   planetSymbol:'♂', zodiac:['Virgo','Aries','Capricorn'], accentColor:'#EA580C', accentColorLight:'#FEF3C7', color:['Orange','Red-Orange','Brown'], transparency:'translucent', mines:['India','Brazil','Uruguay'],                                    qualities:['A','AA'],                          weightRange:{min:5,max:30},  hardness:7,  family:'Chalcedony',  description:'Carnelian is an orange-red stone of vitality and courage, resonating with Mars energy.', astrologicalBenefits:['Motivation','Creativity','Courage','Physical vitality','Sacral chakra activation'], whoShouldWear:'Sub-stone for Mars.', bestMetal:'Copper or Gold', wearingFinger:'Ring finger', featured:false, isNavRatan:false },
  { slug:'triangular-coral', name:'Triangular Coral',  nameHindi:'त्रिकोण मूंगा', planet:'Mars', planetSymbol:'♂', zodiac:['Aries','Scorpio'],    accentColor:'#F97316', accentColorLight:'#FEF3C7', color:['Red','Ox Blood'],             transparency:'opaque',      mines:['Mediterranean Sea','Japan'],                                   qualities:['Triangular-A','Triangular-B'],      weightRange:{min:5,max:15},  hardness:3.5,family:'Organic',     description:'Triangular Coral is a specially shaped variety of Red Coral used for specific Mangal dosh remedies in Vedic astrology.', astrologicalBenefits:['Mangal dosh remedy','Mars pacification','Courage','Protection','Vitality'], whoShouldWear:'Specifically for Manglik individuals.', bestMetal:'Gold', wearingFinger:'Ring finger', featured:false, isNavRatan:false },
  { slug:'malachite',       name:'Malachite',          nameHindi:'मैलाकाइट',  planet:'Venus',  planetSymbol:'♀', zodiac:['Taurus','Capricorn'],       accentColor:'#16A34A', accentColorLight:'#DCFCE7', color:['Green with Banded Patterns'],   transparency:'opaque',      mines:['Democratic Republic of Congo','Russia','Australia'],           qualities:['A','AA'],                          weightRange:{min:5,max:30},  hardness:4,  family:'Monoclinic',  description:'Malachite, with its striking green banded patterns, is a stone of transformation and Venus energy.', astrologicalBenefits:['Transformation','Protection','Heart chakra healing','Emotional release','Business success'], whoShouldWear:'For Venus-influenced and Taurus ascendants.', bestMetal:'Gold or Copper', wearingFinger:'Ring finger', featured:false, isNavRatan:false },
  { slug:'jade',            name:'Jade',               nameHindi:'जेड',       planet:'Jupiter', planetSymbol:'♃', zodiac:['Aries','Taurus','Libra'],  accentColor:'#15803D', accentColorLight:'#DCFCE7', color:['Green','White','Lavender','Yellow'], transparency:'translucent', mines:['Myanmar','China','Guatemala'],                                qualities:['A','AA','Imperial'],               weightRange:{min:5,max:30},  hardness:7,  family:'Jadeite/Nephrite', description:'Jade, the imperial stone of Asia, resonates with Jupiter energy, bringing abundance, wisdom, and longevity.', astrologicalBenefits:['Abundance','Wisdom','Longevity','Protection','Luck & fortune'], whoShouldWear:'For Jupiter-influenced ascendants.', bestMetal:'Gold or Silver', wearingFinger:'Index finger', featured:false, isNavRatan:false },
];

// ── Models ───────────────────────────────────────────────────────────────────
const gemSchema = new mongoose.Schema({
  slug: { type: String, required: true, unique: true },
  name: String, nameHindi: String, planet: String, planetSymbol: String,
  zodiac: [String], accentColor: String, accentColorLight: String,
  color: [String], transparency: String, mines: [String], qualities: [String],
  weightRange: { min: Number, max: Number },
  hardness: Number, family: String, description: String,
  astrologicalBenefits: [String], whoShouldWear: String,
  bestMetal: String, wearingFinger: String,
  featured: Boolean, isNavRatan: Boolean, isActive: { type: Boolean, default: true },
  createdAt: { type: Date, default: Date.now },
});
const Gem = mongoose.model('Gem', gemSchema);

const userSchema = new mongoose.Schema({
  name: String,
  email: { type: String, unique: true, lowercase: true },
  password: String,
  role: { type: String, default: 'customer' },
  isActive: { type: Boolean, default: true },
});
const User = mongoose.model('User', userSchema);

// ── Main ─────────────────────────────────────────────────────────────────────
async function seed() {
  const args = process.argv.slice(2);
  const wipe  = args.includes('--wipe');
  const admin = args.includes('--admin');

  await mongoose.connect(process.env.MONGO_URI);
  console.log('✅ Connected to MongoDB');

  if (wipe) {
    await Gem.deleteMany({});
    console.log('🗑  Gems collection wiped');
  }

  // ── Seed gems ──────────────────────────────────────────────────────────────
  let inserted = 0, skipped = 0;
  for (const gem of GEMS) {
    const exists = await Gem.findOne({ slug: gem.slug });
    if (exists) { skipped++; continue; }
    await Gem.create(gem);
    inserted++;
    process.stdout.write(`\r   → Seeded ${inserted} gems`);
  }
  console.log(`\n📦  Gems: ${inserted} inserted, ${skipped} already existed`);

  // ── Create default admin ───────────────────────────────────────────────────
  if (admin) {
    const ADMIN_EMAIL = 'admin@ratnawala.com';
    const ADMIN_PASS  = 'Admin@1234';
    const hash = await bcrypt.hash(ADMIN_PASS, 12);

    await User.findOneAndUpdate(
      { email: ADMIN_EMAIL },
      { name: 'Ratnawala Admin', email: ADMIN_EMAIL, password: hash, role: 'admin', isActive: true },
      { upsert: true }
    );
    console.log(`👤  Admin user ready → ${ADMIN_EMAIL} / ${ADMIN_PASS}`);
  }

  await mongoose.disconnect();
  console.log('🏁  Seed complete');
  process.exit(0);
}

seed().catch(err => {
  console.error('❌ Seed failed:', err.message);
  process.exit(1);
});
